<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
if(Session::has('userbackend')){

    $user = Session::get('userbackend');
}
(new OverallHelper)->CallLayout(); ?>
<?php $aviao = Data::get('aviao') ?>
    <div id="wrapper">

        <div class="container-fluid">
            <h3 class="text-dark mb-4">Profile</h3>
                <div class="col-lg-12">
                    <div class="row">
                        <div class="col">
                            <div class="card shadow mb-3">
                                <div class="card-header py-3">
                                    <p class="text-primary m-0 fw-bold">User Settings</p>
                                </div>
                                <div class="card-body">
                                    <form method="post" action="<?=Url::toRoute('user/update', $user->id)?>">
                                        <div class="row">
                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="username"><strong>Username</strong></label><input class="form-control" type="text" id="username" placeholder="username" name="username" value="<?= $user->username ?>"></div>
                                            </div>
                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="email"><strong>Email Address</strong></label><input disabled class="form-control" type="email" id="email" placeholder="user@example.com" name="email" value="<?= $user->email ?>"></div>
                                            </div>

                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="nome"><strong>Nome</strong></label><input class="form-control" type="text" id="nome" name="nome" value="<?= $user->nome ?>"></div>
                                            </div>

                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="nif"><strong>NIF</strong></label><input required class="form-control" type="text" id="nif" value="<?= $user->nif ?>" name="nif"></div>
                                            </div>
                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="telefone"><strong>Telephone Number</strong></label><input class="form-control" type="text" id="telefone" value="<?= $user->telefone ?>" name="telefone"></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <div class="mb-3"><label class="form-label" for="morada"><strong>Address</strong></label><input class="form-control" type="text" id="morada" name="morada" value="<?= $user->morada ?>"></div>
                                            </div>


                                        </div>
                                        <div class="mb-3"><button class="btn btn-primary btn-sm" type="submit">Save</button></div>
                                    </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php Layout::includeLayout('footer')?>