<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$role = Session::get('role');
$loggeduser = Session::get('userbackend');
(new OverallHelper)->CallLayout(); ?>
<?php $user = Data::get('cliente'); ?>

          <div class="container-fluid">
    <h3 class="text-dark mb-4">Utilizadores:</h3>
    <div class="card shadow">
        <div class="card-header py-3">
            <p class="text-primary m-0 fw-bold">Informação dos Utilizadores</p>
        </div>
        <div class="card-body">
            <div class="row">


            </div>
            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                <table class="table my-0" id="dataTable">
                    <thead>
                    <tr>


                        <th>Id Utilizador</th>
                        <th>Nome Utilizador</th>
                        <th>Morada</th>
                        <th>Email</th>
                        <th>NIF</th>
                        <th>Telefone</th>
                        <th>Role</th>

                    </tr>
                    </thead>


                    <tbody>
                    <tr>

                        <?php $totalid = 0  ?>
                        <?php foreach ($user as $users) { ?>
                    <tr>
                        <td><?=$users->id?></td>
                        <?php $totalid = $users->id ?>
                        <td><?=$users->nome?></td>
                        <td><?=$users->email?></td>
                        <td><?=$users->morada?></td>
                        <td><?=$users->nif?></td>
                        <td><?=$users->telefone?></td>
                        <td><?=$users->role?></td>

                        <td>
<?php if ($loggeduser->id == $users->id){ ?>
                            <a href="<?=Url::toRoute('user/editusers', $users->id)?>" class="btn btn-warning" disabled="true" role="button">Edit</a>
                            <a href="<?=Url::toRoute('user/destroy', $users->id)?>" class="btn btn-danger" disabled="true" role="button">Delete</a>

                    <?php }else{ ?>
                        <a href="<?=Url::toRoute('user/editusers', $users->id)?>" class="btn btn-warning" role="button">Edit</a>
                        <a href="<?=Url::toRoute('user/destroy', $users->id)?>" class="btn btn-danger" role="button">Delete</a>

                    <?php } ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tr>
                    </tbody>

                </table>
            </div>
            <div class="row">
                <div class="col-md-6 align-self-center">
                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Total de Utilizadores: <?= $totalid ?></p>
                </div>

            </div>
        </div>
    </div>
</div>
    </div>
    </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
<?php Layout::includeLayout('footer')?>