<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
$voo = Data::get('voo');
$passagem = Data::get('passagem');
$passagemTotal = Data::get('passagemtotal');

(new OverallHelper)->CallLayout(); ?>
    <!-- container -->


                <div class="container-fluid">


                    <h3 class="text-dark mb-4">Passagem Vendas:</h3>
                       <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Editar Passagem Vendas</p>
                        </div>
                        <div class="card-body">
                            <div class="row">


                            </div>
                           <form method="post" action="<?=Url::toRoute('passagemvenda/update', $passagem->id)?>">
                               <div class="top-margin">
                                   <label>Id Voos<span class="text-danger">*</span></label>
                                   <br>
                                   <select class="form-control " name="id_voos">

                                       <option><?=$passagem->id_voos?></option>



                                       <?php foreach ($voo as $voos) { ?>
                                           <option><?=$voos->id?></option>
                                       <?php          }?>

                                   </select>
                                   <br>
                                   <label>Tipo Bilhete<span class="text-danger">*</span></label>
                                   <br>
                                   <select class="form-control " name="tipo_bilhete">

                                       <option value="ida" >ida</option>



                                           <option value="ida_volta">ida/Volta</option>


                                   </select>
                                   <br>
                                   <label>Preço<span class="text-danger">*</span></label>
                                   <br>
                                   <input type="text" name="preco" value="<?=$passagem->preco?>" class="form-control">
                                   <br>
                                    <label>CheckIn<span class="text-danger">*</span></label>
                                   <br>
                                   <select class="form-control " name="checkin">
                                       <option value="0">Pendente</option>
                                       <option value="1">Autorizado</option>
                                   </select>
                                   <br>


                               </div>
                               <hr>
                               <div class="row">

                                   <div class="col-lg-4 text-left">
                                       <button class="btn btn-info" type="submit">Editar Passagem</button>
                                   </div>
                               </div>
                           </form>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
<?php Layout::includeLayout('footer')?>