<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$role = Session::get('role');
(new OverallHelper)->CallLayout(); ?>
<?php $passagem = Data::get('passagem'); ?>
<?php $cliente = Data::get('cliente'); ?>

          <div class="container-fluid">
<?php if($role !="operadorcheckin"){ ?>
    <a href="<?=Url::toRoute('passagemvenda/create') ?>" class="btn btn-success" style="float: right;" role="button">Adicionar Passagem</a>
<?php } ?>
    <h3 class="text-dark mb-4">Passagens:</h3>
    <div class="card shadow">
        <div class="card-header py-3">
            <p class="text-primary m-0 fw-bold">Informação das Passagens compradas</p>
        </div>
        <div class="card-body">
            <div class="row">


            </div>
            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                <table class="table my-0" id="dataTable">
                    <thead>
                    <tr>
                        <th>Id Passagem</th>
                        <th>Id Voo</th>
                        <th>Nome Utilizador</th>
                        <th>Tipo de Bilhete</th>
                        <th>Preço do Bilhete</th>
                        <th>checkin</th>

                    </tr>
                    </thead>


                    <tbody>
                    <tr>

                        <?php $totalid = 0  ?>
                        <?php foreach ($passagem as $passagens) { ?>
                    <tr>
                        <td><?=$passagens->id?></td>
                        <?php $totalid = $passagens->id ?>
                        <td><?=$passagens->id_voos?></td>
    <?php  foreach ($cliente as $clientes) {
                            if ($clientes->id == $passagens->id_utilizador){?>
                                <td><?=$clientes->nome?></td>
                            <?php }
                        } ?>
                        <td><?=$passagens->tipo_bilhete?></td>
                        <td><?=$passagens->preco?></td>
                        <?php if ($passagens->checkin == 0){?>
                                <td style="color: #0C70B7;">Pendente</td>
                            <?php }else{?>
                        <td style="color: green">Autorizado</td>
                        <?php }?>
                        <td>
                            <?php if($passagens->checkin != 1){ ?>
                            <a href="<?=Url::toRoute('passagemvenda/checkin', $passagens->id)?>" class="btn btn-success" role="button">CheckIn</a>
                            <?php } ?>
    <?php if($role !="operadorcheckin"){ ?>
                            <a href="<?=Url::toRoute('passagemvenda/edit', $passagens->id)?>" class="btn btn-warning" role="button">Edit</a>
                            <a href="<?=Url::toRoute('passagemvenda/destroy', $passagens->id)?>" class="btn btn-danger" role="button">Delete</a>
    <?php } ?>
                        </td>
                    </tr>
                    <?php } ?>
                    </tr>
                    </tbody>

                </table>
            </div>
            <div class="row">
                <div class="col-md-6 align-self-center">
                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Total de Passagens: <?= $totalid ?></p>
                </div>

            </div>
        </div>
    </div>
</div>
    </div>
    </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
<?php Layout::includeLayout('footer')?>