<footer class="bg-white sticky-footer">
    <div class="container my-auto">
            <div class="text-center my-auto copyright"><span>Copyright © TSN WEBSITES 2021</span></div>
    </div>
</footer>
<!-- JavaScript libs are placed at the end of the document so the pages load faster -->

<?php
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
?>

<?=AssetBundler::js()?>

<script>hljs.initHighlightingOnLoad();</script>

</body>
</html>