<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

if(Session::has('user')){

    $user = Session::get('user');
}
    $escala = Data::get('escalas');
    $aeroporto = Data::get('aeroporto');



Layout::includeLayout('indexheader'); ?>




    <section id="home" class="about-us" style="background: url(<?= Asset::image('home/banner.jpg')?>)no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;)">
        <div class="container">
            <div class="about-us-content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="single-about-us">
                            <div class="about-us-txt">
                                <h2>
                                    Explore <the></the> Beauty of the Beautiful World

                                </h2>

                            </div><!--/.about-us-txt-->
                        </div><!--/.single-about-us-->
                    </div><!--/.col-->
                    <div class="col-sm-0">
                        <div class="single-about-us">

                        </div><!--/.single-about-us-->
                    </div><!--/.col-->
                </div><!--/.row-->
            </div><!--/.about-us-content-->
        </div><!--/.container-->

    </section><!--/.about-us-->
    <!--about-us end -->

    <!--travel-box start-->

    <section  class="travel-box">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="single-travel-boxes">
                        <div id="desc-tabs" class="desc-tabs">

                            <ul class="nav nav-tabs" role="tablist">


                                <li role="presentation">
                                    <a href="#flights" aria-controls="flights" role="tab" data-toggle="tab">
                                        <i class="fa fa-plane"></i>
                                        flights
                                    </a>
                                </li>
                         
                            </ul>

                            <!-- Tab panes -->
                            <form action="<?= URL::toRoute("home/search") ?>"  method="post">
                            <div class="tab-content">


                                <div role="tabpanel" class="tab-pane active fade in" id="flights">
                                    <div class="tab-para">
                        
                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-12">
                                                <div class="single-tab-select-box">

                                                    <h2>Aeroporto Origem</h2>

                                                    <div class="travel-select-icon">
                                                        <select class="form-control " name="aeroporto_origem">

                                                            <option value="">enter your location</option><!-- /.option-->



                                                                <?php foreach ($aeroporto as $aeroportos) { ?>
                                                                        <option value="<?=$aeroportos->id?>"><?=$aeroportos->nome?></option>
                                                                <?php          }?>

                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            <div class="col-lg-2 col-md-3 col-sm-4">
                                                <div class="single-tab-select-box">
                                                    <h2>Origem</h2>
                                                    <div class="travel-check-icon">
                                                            <input type="datetime-local" name="data_origem"  class="form-control" data-provide="datepicker" value="">

                                                    </div><!-- /.travel-check-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            <div class="col-lg-2 col-md-3 col-sm-4">
                                                <div class="single-tab-select-box">
                                                    <h2>Destino</h2>
                                                    <div class="travel-check-icon">
                                                            <input type="datetime-local" name="data_destino" class="form-control" data-toggle="datepicker"  value="">

                                                    </div><!-- /.travel-check-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-12">
                                                <div class="single-tab-select-box">

                                                    <h2>Aeroporto Destino</h2>

                                                    <div class="travel-select-icon">
                                                        <select class="form-control " name="aeroporto_destino">

                                                            <option value="">enter your destination location</option><!-- /.option-->


                                                            <?php foreach ($aeroporto as $aeroportos) { ?>
                                                                <option value="<?=$aeroportos->id?>"><?=$aeroportos->nome?></option>
                                                            <?php          }?>
                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->

                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            </div><!--/.col-->
                                            <div class="clo-sm-5">
                                                <div class="about-btn pull-right">
                                                    <button  class="about-view travel-btn" type="submit">
                                                        search
                                                    </button><!--/.travel-btn-->
                                                </div><!--/.about-btn-->
                                            </div><!--/.col-->

                                        </div><!--/.row-->

                                    </div>

                                </div><!--/.tabpannel-->


                            </form>

                        </div><!--/.desc-tabs-->
                    </div><!--/.desc-tabs-->
                    </div><!--/.single-travel-box-->
                </div><!--/.col-->
            </div><!--/.row-->
        </div><!--/.container-->

    </section><!--/.travel-box-->



    <!-- testemonial Start -->
    <section   class="testemonial">
        <div class="container">

            <div class="gallary-header text-center">
                <h2>
                    clients reviews
                </h2>
                <p>
                    Duis aute irure dolor in  velit esse cillum dolore eu fugiat nulla.
                </p>

            </div><!--/.gallery-header-->

            <div class="owl-carousel owl-theme" id="testemonial-carousel">

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                                <img src="<?= Asset::image('review.jpg')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Foi simples, rápido e eficaz.
                            </p>
                            <h3>
                                <a href="#">
                                    Vladyslav Bobko
                                </a>
                            </h3>
                            <h4>Leiria, Portugal</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review1.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Simplemente fantástico, me encanta esta empresa.
                            </p>
                            <h3>
                                <a href="#">
                                    Juan perez
                                </a>
                            </h3>
                            <h4>Tijuana, Mexico</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review3.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Non ho mai visto un'azienda così sicura ed economica
                            </p>
                            <h3>
                                <a href="#">
                                    Marco Belli
                                </a>
                            </h3>
                            <h4>Roma, Italy</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review2.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>

                                Sans aucun doute 5 étoiles
                            </p>
                            <h3>
                                <a href="#">
                                    Julius Claire
                                </a>
                            </h3>
                            <h4>Paris, France</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="assets/images/client/testimonial2.jpg" alt="img"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                            </p>
                            <h3>
                                <a href="#">
                                    kevin watson
                                </a>
                            </h3>
                            <h4>london, england</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="assets/images/client/testimonial1.jpg" alt="img"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                            </p>
                            <h3>
                                <a href="#">
                                    kevin watson
                                </a>
                            </h3>
                            <h4>london, england</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="assets/images/client/testimonial1.jpg" alt="img"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                            </p>
                            <h3>
                                <a href="#">
                                    kevin watson
                                </a>
                            </h3>
                            <h4>london, england</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="assets/images/client/testimonial2.jpg" alt="img"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                            </p>
                            <h3>
                                <a href="#">
                                    kevin watson
                                </a>
                            </h3>
                            <h4>london, england</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="assets/images/client/testimonial1.jpg" alt="img"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Lorem ipsum dolor sit amet, contur adip elit, sed do mod incid ut labore et dolore magna aliqua. Ut enim ad minim veniam.
                            </p>
                            <h3>
                                <a href="#">
                                    kevin watson
                                </a>
                            </h3>
                            <h4>london, england</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

            </div><!--/.testemonial-carousel-->
        </div><!--/.container-->

    </section><!--/.testimonial-->
    <!-- testemonial End -->






</body>
<?php Layout::includeLayout('footer')?>