<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>




    <section id="home" class="about-us" style="background: url(<?= Asset::image('home/banner.jpg')?>)no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;)">
        <div class="container">
            <div class="about-us-content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="single-about-us">
                            <div class="about-us-txt">
                                <h2>
                                    Explore the Beauty of the Beautiful World

                                </h2>
                                <div class="about-btn">
                                    <button  class="about-view">
                                        explore now
                                    </button>
                                </div><!--/.about-btn-->
                            </div><!--/.about-us-txt-->
                        </div><!--/.single-about-us-->
                    </div><!--/.col-->
                    <div class="col-sm-0">
                        <div class="single-about-us">

                        </div><!--/.single-about-us-->
                    </div><!--/.col-->
                </div><!--/.row-->
            </div><!--/.about-us-content-->
        </div><!--/.container-->

    </section><!--/.about-us-->
    <!--about-us end -->

    <!--travel-box start-->
    <section  class="travel-box">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="single-travel-boxes">
                        <div id="desc-tabs" class="desc-tabs">

                            <ul class="nav nav-tabs" role="tablist">


                                <li role="presentation">
                                    <a href="#flights" aria-controls="flights" role="tab" data-toggle="tab">
                                        <i class="fa fa-plane"></i>
                                        flights
                                    </a>
                                </li>
                            </ul>

                            <!-- Tab panes -->
                            <div class="tab-content">


                                <div role="tabpanel" class="tab-pane active fade in" id="flights">
                                    <div class="tab-para">
                        
                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-12">
                                                <div class="single-tab-select-box">

                                                    <h2>Aeroporto Origem</h2>

                                                    <div class="travel-select-icon">
                                                        <select class="form-control ">

                                                            <option value="default">enter your location</option><!-- /.option-->

                                                            <option value="faro_PT">Faro, Portugal</option><!-- /.option-->
                                                            <option value="lisboa_PT">Lisboa, Portugal</option><!-- /.option-->


                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            <div class="col-lg-2 col-md-3 col-sm-4">
                                                <div class="single-tab-select-box">
                                                    <h2>Origem</h2>
                                                    <div class="travel-check-icon">
                                                        <form action="#">
                                                            <input type="text" name="departure" class="form-control" data-toggle="datepicker"
                                                                   placeholder="12 -01 - 2017 ">
                                                        </form>
                                                    </div><!-- /.travel-check-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            <div class="col-lg-2 col-md-3 col-sm-4">
                                                <div class="single-tab-select-box">
                                                    <h2>Destino</h2>
                                                    <div class="travel-check-icon">
                                                        <form action="#">
                                                            <input type="text" name="return" class="form-control" data-toggle="datepicker" placeholder="22 -01 - 2017 ">
                                                        </form>
                                                    </div><!-- /.travel-check-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->

                                            <div class="col-lg-2 col-md-1 col-sm-4">
                                                <div class="single-tab-select-box">
                                                    <h2>Bilhetes <a title="Infelizmente a compra maxima de bilhetes será limitada até 10. Em caso de duvida, contacte o suporte."> ﹖</a></h2>
                                                    <div class="travel-select-icon">
                                                        <select class="form-control ">

                                                            <option value="default">1</option><!-- /.option-->
                                                            <option value="2">2</option><!-- /.option-->
                                                            <option value="3">3</option><!-- /.option-->
                                                            <option value="4">4</option><!-- /.option-->
                                                            <option value="5">5</option><!-- /.option-->
                                                            <option value="6">6</option><!-- /.option-->
                                                            <option value="7">7</option><!-- /.option-->
                                                            <option value="8">8</option><!-- /.option-->
                                                            <option value="9">9</option><!-- /.option-->
                                                            <option value="10">10</option><!-- /.option-->

                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->


                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-12">
                                                <div class="single-tab-select-box">

                                                    <h2>Aeroporto Destino</h2>

                                                    <div class="travel-select-icon">
                                                        <select class="form-control ">

                                                            <option value="default">Selecione o Destino.</option><!-- /.option-->

                                                            <option value="lisboa_PT">Lisboa, Portugal</option><!-- /.option-->
                                                            <option value="porto_PT">Porto, Portugal</option><!-- /.option-->
                                                            <option value="faro_PT">Faro, Portugal</option><!-- /.option-->
                                                            <option value="madeira_PT">Madeira, Portugal</option><!-- /.option-->
                                                            <option value="acores_PT">Açores, Portugal</option><!-- /.option-->
                                                            <option value="madrid_ES">Madrid, Spain</option><!-- /.option-->
                                                            <option value="leon_ES">León, Spain</option><!-- /.option-->
                                                            <option value="lleida_ES">Lleida, Spain</option><!-- /.option-->
                                                            <option value="malaga_ES">Málaga, Spain</option><!-- /.option-->
                                                            <option value="salamanca_ES">Salamanca, Spain</option><!-- /.option-->
                                                            <option value="gap_FR">Gap, France</option><!-- /.option-->

                                                            <option value="lurcyLevis_FR">Lurcy-Lévis, France</option><!-- /.option-->
                                                            <option value="sedan_FR">Sedan, France</option><!-- /.option-->
                                                            <option value="puivert_FR">Puivert, France</option><!-- /.option-->
                                                            <option value="foggia_IT">Foggia, Italy</option><!-- /.option-->
                                                            <option value="bari_IT">Bari, Italy</option><!-- /.option-->
                                                            <option value="taranto_IT">Taranto, Italy</option><!-- /.option-->
                                                            <option value="capua_IT">Capua, Italy</option><!-- /.option-->
                                                            <option value="naples_IT">Naples, Italy</option><!-- /.option-->
                                                            <option value="alamos_MX">Álamos, Mexico</option><!-- /.option-->
                                                            <option value="canacea_MX">Cananea, Mexico</option><!-- /.option-->
                                                            <option value="cuidadAcuna_MX">Ciudad Acuña, Mexico</option><!-- /.option-->
                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->

                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->
                                            <div class="col-lg-3 col-md-3 col-sm-4">
                                                <div class="single-tab-select-box">

                                                    <h2>Escala</h2>
                                                    <div class="travel-select-icon">
                                                        <select class="form-control ">

                                                            <option value="default">Selecione a escala</option><!-- /.option-->

                                                            <option value="A">A</option><!-- /.option-->

                                                            <option value="B">B</option><!-- /.option-->
                                                            <option value="C">C</option><!-- /.option-->

                                                        </select><!-- /.select-->
                                                    </div><!-- /.travel-select-icon -->
                                                </div><!--/.single-tab-select-box-->
                                            </div><!--/.col-->
                                            <div class="clo-sm-5">
                                                <div class="about-btn pull-right">
                                                    <button  class="about-view travel-btn">
                                                        search
                                                    </button><!--/.travel-btn-->
                                                </div><!--/.about-btn-->
                                            </div><!--/.col-->



                                        </div><!--/.row-->

                                            <div class="row">
                                                <div class="col-lg-4 col-md-4 col-sm-4">
                                                    <div class="single-tab-select-box">
                                                       <h2><input type="checkbox" id="idaVolta" name="idaVolta">
                                                       Ida/Volta
                                                       </h2>


                                                    </div><!--/.single-tab-select-box-->
                                                </div><!--/.col-->
                                            </div>

                                    </div>

                                </div><!--/.tabpannel-->

                            </div><!--/.tab content-->
                        </div><!--/.desc-tabs-->
                    </div><!--/.single-travel-box-->
                </div><!--/.col-->
            </div><!--/.row-->
        </div><!--/.container-->

    </section><!--/.travel-box-->
    <!--travel-box end-->

    <!--service start-->
    <section id="service" class="service">
        <div class="container">

            <div class="service-counter text-center">

                <div class="col-md-4 col-sm-4">
                    <div class="single-service-box">
                        <div class="service-img">
                            <img src="assets/images/service/s1.png" alt="service-icon" />
                        </div><!--/.service-img-->
                        <div class="service-content">
                            <h2>
                                <a href="#">
                                    amazing tour packages
                                </a>
                            </h2>
                            <p>Duis aute irure dolor in  velit esse cillum dolore eu fugiat nulla.</p>
                        </div><!--/.service-content-->
                    </div><!--/.single-service-box-->
                </div><!--/.col-->

                <div class="col-md-4 col-sm-4">
                    <div class="single-service-box">
                        <div class="service-img">
                            <img src="" alt="service-icon" />
                        </div><!--/.service-img-->
                        <div class="service-content">
                            <h2>
                                <a href="#">
                                    book top class hotel
                                </a>
                            </h2>
                            <p>Duis aute irure dolor in  velit esse cillum dolore eu fugiat nulla.</p>
                        </div><!--/.service-content-->
                    </div><!--/.single-service-box-->
                </div><!--/.col-->

                <div class="col-md-4 col-sm-4">
                    <div class="single-service-box">
                        <div class="statistics-img">
                            <img src="assets/images/service/s3.png" alt="service-icon" />
                        </div><!--/.service-img-->
                        <div class="service-content">

                            <h2>
                                <a href="#">
                                    online flight booking
                                </a>
                            </h2>
                            <p>Duis aute irure dolor in  velit esse cillum dolore eu fugiat nulla.</p>
                        </div><!--/.service-content-->
                    </div><!--/.single-service-box-->
                </div><!--/.col-->

            </div><!--/.statistics-counter-->
        </div><!--/.container-->

    </section><!--/.service-->
    <!--service end-->

    <!-- testemonial Start -->
    <section   class="testemonial">
        <div class="container">

            <div class="gallary-header text-center">
                <h2>
                    clients reviews
                </h2>
                <p>
                    Duis aute irure dolor in  velit esse cillum dolore eu fugiat nulla.
                </p>

            </div><!--/.gallery-header-->

            <div class="owl-carousel owl-theme" id="testemonial-carousel">

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review.jpg')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Foi simples, rápido e eficaz.
                            </p>
                            <h3>
                                <a href="#">
                                    Vladyslav Bobko
                                </a>
                            </h3>
                            <h4>Leiria, Portugal</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review_wide.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Siiiiimplyyyyyyyy woooondeeerfuuuuuul, IIIIII loooooooveeeee thiiiiiiiiis cooooooompaaaaaanyyyyyyy.
                            </p>
                            <h3>
                                <a href="#">
                                    Wide Vlad
                                </a>
                            </h3>
                            <h4>Pc do Vlad, Portugal</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review1.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Simplemente fantástico, me encanta esta empresa.
                            </p>
                            <h3>
                                <a href="#">
                                    Juan perez
                                </a>
                            </h3>
                            <h4>Tijuana, Mexico</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review3.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>
                                Non ho mai visto un'azienda così sicura ed economica
                            </p>
                            <h3>
                                <a href="#">
                                    Marco Belli
                                </a>
                            </h3>
                            <h4>Roma, Italy</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

                <div class="home1-testm item">
                    <div class="home1-testm-single text-center">
                        <div class="home1-testm-img">
                            <img src="<?= Asset::image('review2.png')?>"/>
                        </div><!--/.home1-testm-img-->
                        <div class="home1-testm-txt">
								<span class="icon section-icon">
									<i class="fa fa-quote-left" aria-hidden="true"></i>
								</span>
                            <p>

                                Sans aucun doute 5 étoiles
                            </p>
                            <h3>
                                <a href="#">
                                    Julius Claire
                                </a>
                            </h3>
                            <h4>Paris, France</h4>
                        </div><!--/.home1-testm-txt-->
                    </div><!--/.home1-testm-single-->

                </div><!--/.item-->

            </div><!--/.testemonial-carousel-->
        </div><!--/.container-->

    </section><!--/.testimonial-->
    <!-- testemonial End -->






</body>
<?php Layout::includeLayout('footer')?>