<?php

use ArmoredCore\WebObjects\Asset;
use ArmoredCore\Facades\AssetBundler;
use ArmoredCore\Facades\DebugRenderer;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

if(Session::has('user')){

    $user = Session::get('user');
}

?>

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Silvio Priem Mendes, PhD">

    <title>Weblogic MVC</title>

    <?= AssetBundler::css() ?>

    <link rel="shortcut icon" href="<?= Asset::image('gt_favicon.png') ?>">
    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- Custom styles for our site template -->
    <link rel="stylesheet" href="<?= Asset::css('/bootstrap-theme.css') ?>" media="screen">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?= Asset::js('html5shiv.js') ?>"></script>
    <script src="<?= Asset::js('respond.min.js') ?>"></script>

		<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
<!-- Fixed navbar -->
<div class="navbar navbar-fixed-top">
    <!-- main-menu Start -->
    <header class="top-area">
        <div class="header-area">
            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="logo">
                            <a href="<?= Url::toRoute('home/index') ?>">
                                FlightTravel<span>Air</span>
                            </a>
                        </div><!-- /.logo-->
                    </div><!-- /.col-->
                    <div class="col-sm-10">
                        <div class="main-menu">

                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse"
                                        data-target=".navbar-collapse">
                                    <i class="fa fa-bars"></i>
                                </button><!-- / button-->
                            </div><!-- /.navbar-header-->
                            <div class="collapse navbar-collapse">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="smooth-menu"><a href="<?= Url::toRoute('home/index') ?>">home</a></li>
                                         <li>


                                        <a class="book-btn" href="<?= Url::toRoute('home/search') ?>">book now
                                        </a></li>
                                    <li>
                                        <?php if(isset($user)){?>
                                            <style>.dropbtn {
                                                    color: white;
                                                    padding: 16px;
                                                    font-size: 16px;
                                                    border: none;
                                                }

                                                /* The container <div> - needed to position the dropdown content */
                                                .dropdown {
                                                    position: relative;
                                                    display: inline-block;
                                                }

                                                /* Dropdown Content (Hidden by Default) */
                                                .dropdown-content {
                                                    display: none;
                                                    position: absolute;
                                                    background-color: #3939A5;
                                                    min-width: 160px;
                                                    box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                                                    z-index: 1;
                                                }

                                                /* Links inside the dropdown */
                                                .dropdown-content a {
                                                    color: black;
                                                    padding: 12px 16px;
                                                    text-decoration: none;
                                                    display: block;
                                                }

                                                /* Change color of dropdown links on hover */
                                                .dropdown-content a:hover {background-color: #ddd;}

                                                /* Show the dropdown menu on hover */
                                                .dropdown:hover .dropdown-content {display: block;}

                                                /* Change the background color of the dropdown button when the dropdown content is shown */
                                                </style>

                                                            <div class="dropdown">
                                                                <a class="dropbtn"><?= $user->email ?></a>
                                                                <div class="dropdown-content">
                                                                    <a href="<?= Url::toRoute('user/perfil') ?>">Perfil</a>
                                                                    <a href="<?= Url::toRoute('user/historico') ?>">Historico de Voos</a>
                                                                    <a href="<?= Url::toRoute('user/logout') ?>">logout</a>
                                                                </div>
                                                            </div>
                                    <?php  }else{ ?>
                                        <li class="smooth-menu"><a href="<?= Url::toRoute('home/login') ?>">login </a></li>


                                    <?php }  ?>
                                    </li>
                                    <!--/.project-btn-->
                                </ul>
                            </div><!-- /.navbar-collapse -->
                        </div><!-- /.main-menu-->
                    </div><!-- /.col-->
                </div><!-- /.row -->
            </div><!-- /.container-->
        </div><!-- /.header-area -->

    </header><!-- /.top-area-->
    <!-- main-menu End -->
</div>

