<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>

	<!-- container -->
    <body class="bg-gradient-primary">
    <div class="container" style="padding-top: 10%;">
        <div class="row justify-content-center">
            <div class="col-md-9 col-lg-12 col-xl-10">
                <div class="card shadow-lg o-hidden border-0 my-5">
                    <div class="card-body p-0">
                        <div class="row">
                            <div class="col">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h3 class="text-dark mb-4">Bem-Vindo!</h3>
                                    </div>
                                    <form class="user" method="post" action="<?= Url::toRoute('user/login') ?>">
                                        <div class="form-group" style="margin-bottom: 15px;"><input class="form-control form-control-user" type="email" id="exampleInputEmail" aria-describedby="emailHelp" placeholder="Insira o seu Email" name="email"></div>
                                        <div class="form-group" style="margin-bottom: 15px;"><input class="form-control form-control-user" type="password" id="exampleInputPassword" placeholder="Palavra-passe" name="password"></div>
                                        <button class="btn btn-primary btn-block text-white btn-user" style="width: 100%" type="submit">Login</button>
                                        <hr>
                                    </form>
                                    <div class="alert alert-success" role="alert" id="loginAlert">
                                        <p style="text-align: center;">Incorrect Credential</p>
                                    </div>
                                    <script>
                                        $('#loginAlert').hide();
                                        const urlParams = new URLSearchParams(window.location.search);
                                        const myParam = urlParams.get('error');
                                        if(myParam == "Incorrect_Credential") {
                                            $('#loginAlert').show();
                                        }
                                    </script>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </body>

