<?php
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Redirect;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;
if(Session::has('user')){

    $user = Session::get('user');

}

Layout::includeLayout('indexheader') ?>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="index.html">Home</a></li>
			<li class="active">User access</li>
		</ol>

		<div class="row">
			
			<!-- Article main content -->
			<article class="col-xs-12 maincontent">
				<header class="page-header">
					<h1 class="page-title">Editar</h1>
				</header>
				
				<div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
					<div class="panel panel-default">
						<div class="panel-body">
							<h3 class="thin text-center">Editar perfil</h3>
							<hr>
							
							<form action="<?= Url::toRoute('user/edit') ?>" method="post">
								<div class="top-margin">
									<label>Nome <span class="text-danger">*</span></label>
									<input type="text" name="nome" value="<?= $user->nome ?>" class="form-control">
								</div>
                               <div class="top-margin">
									<label>Email <span class="text-danger">*</span></label>
									<input type="text" disabled name="email" value="<?= $user->email ?>" class="form-control">
								</div>
                                <div class="top-margin">
									<label>Morada</label>
									<input type="text" name="morada" value="<?= $user->morada ?>" class="form-control">
								</div>
                                <div class="top-margin">
									<label>NIF </label>
									<input type="text" name="nif" value="<?= $user->nif ?>" class="form-control">
								</div>
  <div class="top-margin">
									<label>Telefone </label>
									<input type="text" name="telefone" value="<?= $user->telefone ?>" class="form-control">
								</div>


								<hr>

								<div class="row">

									<div class="col-lg-4 text-left">
										<button class="btn btn-action" type="submit">Editar perfil</button>
									</div>
								</div>
							</form>
						</div>
					</div>

				</div>
				
			</article>
			<!-- /Article -->

		</div>
	</div>	<!-- /container -->

<?php Layout::includeLayout('footer') ?>