<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

(new OverallHelper)->CallLayout(); ?>
<?php $voo = Data::get('voo');  ?>

    <!-- container -->


                <div class="container-fluid">


                    <h3 class="text-dark mb-4">Voo:</h3>
                       <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Editar Voo</p>
                        </div>
                        <div class="card-body">
                            <div class="row">


                            </div>
                           <form method="post" action="<?=Url::toRoute('voo/update', $voo->id)?>">
                               <div class="top-margin">
                                   <label>Preço do Voo<span class="text-danger">*</span></label>
                                   <input type="text" name="preco" value="<?=$voo->preco?>" class="form-control">
                               </div>
                               <hr>
                               <div class="row">

                                   <div class="col-lg-4 text-left">
                                       <button class="btn btn-info" type="submit">Editar Voo</button>
                                   </div>
                               </div>
                           </form>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
<?php Layout::includeLayout('footer')?>