<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;

Layout::includeLayout('header') ?>
<?php $voo = Data::get('voos') ?>

    <!-- container -->
    <div class="container">

        <ol class="breadcrumb">
            <li><a href="index.html">Home</a></li>
            <li class="active">Book Index</li>
        </ol>

        <h2 class="text-left top-space">Book Index</h2>
        <h2 class="top-space"></h2>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-striped"><thead><th><h3>Id</h3></th><th><h3>id aviao</h3></th><th><h3>Aeroporto destino</h3></th><th><h3>Aeroporto Origem</h3></th><th><h3>Data Destino</h3></th><th><h3>Data Origem</h3></th><th><h3>Distancia</h3></th><th><h3>Preço</h3></th></thead>
                <tbody>
                <?php foreach ($voo as $voos) { ?>
                    <tr>
                    <td><?=$voos->id?></td>
                    <td><?=$voos->id_aviao?></td>
                    <td><?=$voos->aeroporto_destino?></td>
                    <td><?=$voos->aeroporto_origem?></td>
                    <td><?=$voos->data_origem->format('Y-m-d')?></td>
                    <td><?=$voos->data_destino->format('Y-m-d')?></td>
                    <td><?=$voos->distancia?></td>
                    <td><?=$voos->preco?></td>
                    <td>
                        <a href="<?=Url::toRoute('book/show', $voos->id)?>" class="btn btn-info" role="button">Show</a>
                        <a href="<?=Url::toRoute('book/edit', $voos->id)?>" class="btn btn-info" role="button">Edit</a>
                        <a href="<?=Url::toRoute('book/destroy', $voos->id)?>" class="btn btn-warning" role="button">Delete</a>
                    </td>
                    </tr>
                <?php } ?>

                </tbody>

            </table>

            </div>
            <div class="col-sm-6">
                <h3>Create a new Book</h3>
                <p>
                    <a href="<?=Url::toRoute('book/create')?>" class="btn btn-info" role="button">New</a>
                </p>
            </div>
        </div> <!-- /row -->

    </div>	<!-- /container -->
<?php Layout::includeLayout('footer')?>