<?php use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\URL;

$role = Session::get('role');
(new OverallHelper)->CallLayout(); ?>
<?php $voo = Data::get('voo') ?>
<?php $aeroporto = Data::get('aeroporto') ?>

    <!-- container -->


                <div class="container-fluid">

                    <a href="<?=Url::toRoute('voo/create') ?>" class="btn btn-success" style="float: right;" role="button">Criar Voo</a>

                    <h3 class="text-dark mb-4">Voos:</h3>
                       <div class="card shadow">
                        <div class="card-header py-3">
                            <p class="text-primary m-0 fw-bold">Informação dos Voos</p>
                        </div>
                        <div class="card-body">
                            <div class="row">


                            </div>
                            <div class="table-responsive table mt-2" id="dataTable" role="grid" aria-describedby="dataTable_info">
                                <table class="table my-0" id="dataTable">
                             <thead>
                             <tr>
                                 <th>ID Voo</th>

                                 <th>Aeroporto Inicial</th>
                                 <th>Aeroporto Final</th>
                                 <th>Data Inicial</th>
                                 <th>Data Final</th>
                                 <th>Preço</th>
                                 <th>Estado</th>
                             </tr>
                             </thead>

                                    <tbody>
                                    <tr>
                                        <?php $totalid = 0 ?>
                                        <?php foreach ($voo as $voos) { ?>
                                    <tr>
                                        <td><?=$voos->id?></td>
    <?php foreach ($aeroporto as $aeroportos) { ?>
        <?php if($aeroportos->id== $voos->id_aeroporto_inicial){?>
            <td><?=$aeroportos->nome?></td>
    <?php } ?>
    <?php } ?>
                                        <?php foreach ($aeroporto as $aeroportos) { ?>
                                            <?php if($aeroportos->id== $voos->id_aeroporto_final){?>
                                                <td><?=$aeroportos->nome?></td>
                                            <?php } ?>
                                        <?php } ?>
                                        <td><?=$voos->data_inicial->format('Y-m-d H:i:s')?></td>
                                        <td><?=$voos->data_final->format('Y-m-d H:i:s')?></td>
                                        <td><?= $voos->preco ?></td>
                                        <?php if($voos->estado== "Agendado"){?>
                                        <td style="color: blue"><?= $voos->estado ?></td>
                                        <?php }else{ ?>

                                            <td style="color: limegreen"><?= $voos->estado ?></td>
                                        <?php } ?>
                                        <?php $totalid = $totalid +1 ?>
                                        <td>

                                            <a href="<?=Url::toRoute('escala/show', $voos->id)?>" class="btn btn-secondary" role="button">Escala</a>
                                            <?php if($role !="operadorcheckin"){ ?>
                                                <?php if($voos->estado !="Finalizado"){ ?>
                                                    <a href="<?=Url::toRoute('voo/finish', $voos->id)?>" class="btn btn-success" role="button">Finish</a>
                                                <?php } ?>
                                            <a href="<?=Url::toRoute('voo/edit', $voos->id)?>" class="btn btn-warning" role="button">Edit</a>
                                             <a href="<?=Url::toRoute('voo/destroy', $voos->id)?>" class="btn btn-danger" role="button">Delete</a>

                                            <?php } ?>
                                        </td>
                                    </tr>
                                    </tr>
                                    <?php } ?>
                                    </tr>
                                    </tbody>

                                </table>
                            </div>
                            <div class="row">
                                <div class="col-md-6 align-self-center">
                                    <p id="dataTable_info" class="dataTables_info" role="status" aria-live="polite">Total de Voos: <?= $totalid ?></p>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div><a class="border rounded d-inline scroll-to-top" href="#page-top"><i class="fas fa-angle-up"></i></a>
    </div>
<?php Layout::includeLayout('footer')?>